### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by FUZIK** [MundoSK/MundoSK#14]
current
```
"call custom event %string% [to] [det[ail]s %-objects%] [arg[ument]s %-objects%]"
example
call custom event "hello,world"
```
new
```
"call custom event[s] %strings% [to] [det[ail]s %-objects%] [arg[ument]s %-objects%]"
example
call custom events "hello,world" and "hello in world"
```
ps but you decide

**Comment by TlatoaniHJ** [comment]
Interesting idea, though I have a question about the implementation: are you just trying to call the same event but with multiple names, or do you want multiple different events with different names to be called one after another?

**Comment by FUZIK** [comment]
I'm trying to call the same event with multiple names.

**Comment by TlatoaniHJ** [comment]
The feature has been added in MundoSK 1.7.5-BETA.10.90, along with an addition to the ID of Custom Event expression to accomodate the feature. The new syntax for calling custom event is the same but with `%strings%` (no `event[s]`, only `event`). You can use the `/mundosk doc` command to view the changes fully (the category is `CustomEvent`).
