### ISSUE TITLE
Setting a tab name color bug??

### ISSUE THREAD

**Issue by Efnilite** [MundoSK/MundoSK#15]
Skript Version: dev32d

MundoSK Version: 1.8.2

Minecraft Version: 1.12

So basically, I was setting up a server with colored TAB stuff, etc.
Since I wanted add custom TAB names with the minigames I created, I wanted to create a code
that gives you that TAB name, until it gets changed.

It worked for all of the ranks, excluding OPs

Whenever I tried to use the code with OPs, it would automatically change to PURPLE
I removed a few of my SKRIPT addons, and if I removed MundoSK, it wouldn't change if it were OPs, but then also the code didn't work

CODE:
on join:
	if player has permission "is.DEFAULT":
		set player's nametag to "&7%name of player%"
		set player's tablist name to "&7%name of player%"
	if player has permission "is.PRO":
		set player's nametag to "&3%name of player%"
		set player's tablist name to "&3%name of player%"
	if player has permission "is.PLAT":
		set player's nametag to "&b%name of player%"
		set player's tablist name to "&b%name of player%"
	if player has permission "is.HERO":
		set player's nametag to "&2%name of player%"
		set player's tablist name to "&2%name of player%"
	if player has permission "is.ELITE":
		set player's nametag to "&a%name of player%"
		set player's tablist name to "&a%name of player%"
	if player has permission "is.VETERAN":
		set player's nametag to "&e%name of player%"
		set player's tablist name to "&e%name of player%"
	if player has permission "is.HELPER":
		set player's nametag to "&d%name of player%"
		set player's tablist name to "&d%name of player%"
	if player has permission "is.MOD":
		set player's nametag to "&6%name of player%"
		set player's tablist name to "&6%name of player%"
	if player has permission "is.OWNER":
		set player's nametag to "&4%name of player%"
		set player's tablist name to "&4%name of player%"
	if player has permission "is.DEV":
		set player's nametag to "&5%name of player%"
		set player's tablist name to "&5%name of player%" 

Photos:
https://imgur.com/a/zBhgG

Have you tried looking in the documentation: Yes

Have you tried looking in the forums: Yup

What other methods have you tried to fix it:
Looking thru multiple configs and trying to set it when only the player is an op, but it still goes PURPLE

Plugin List: SkQuery, MundoSK, PEX, Tablist (the plugin that I use the TAB list for, although it didn't have an option in its config file for names), Skript, PlaceholderAPI and Essentials.

Thanks!
- Efnilite

**Comment by KingAlterIV** [comment]
This isn't really a bug... when your op, you get all permissions, and your "is.DEV" is at the end so that's why you get the purple name instead of your red name for owner.

**Comment by Efnilite** [comment]
I just listed the plugins that I thought where the most important, but I am running ProtocolLib.

I was quite stupid here, because I had used the same tactic as you said an hour earlier for ranked join messages, and I realized that it executed ALL possible rank joins. :P

And thanks for the fast response! Thats not somehing you see everyday
