### ISSUE TITLE
SkinsRestorer cannot be used with MundoSK hooked to ProtocolLib

### ISSUE THREAD

**Issue by NanoDankster** [MundoSK/MundoSK#16]
### Bug Report

Skript Version: dev32c

MundoSK Version: 1.8.4

Minecraft Version: 1.12.2

### Steps to Reproduce the Issue
Load the server with the latest ProtocolLib and SkinsRestorer(13.3).
Try to change your skin to a premium skin.
You won't be able to change it.

### Full Code
None.

### Errors on Reload (if applicable)
None.

### Console Errors (if applicable)
None.

### Other Useful Info (ex. addons and plugins you are using)
ProtocolLib v4.3.0

### Troubleshooting

Have you tried looking in the documentation:
No.
Have you tried looking in the forums:
No.
What other methods have you tried to fix it:
Tried to delete plugins one by one. Found out that this addon is responsible.

**Comment by TlatoaniHJ** [comment]
If you go to MundoSK’s config and disable the `enable_custom_skin_and_tablist` setting, SkinRestorer should work. Note that this will prevent you from using MundoSK’s custom tablist syntaxes.

**Comment by Blueyescat** [comment]
Why you need to disable many features to get it working?

**Comment by Snow-Pyon** [comment]
@Blueyescat as there is no official API for this (on Spigot at least), one plugin is overriding the other plugin's functionality, you can't really support every plugin with a similar functionality without an API for it.
