### ISSUE TITLE
Teams, Nametag, Custom Event

### ISSUE THREAD

**Issue by Feerko** [MundoSK/MundoSK#20]
hello :)
when i'm use a version of mundosk <1.8.3 i get bug with teams
tag above player works but not in tab
<img width="628" alt="zrzut_ekranu_2018-04-17_o_11 03 45" src="https://user-images.githubusercontent.com/16988054/38885566-abc37a80-4273-11e8-9666-a25deee5e459.png">

when i'm update it to 1.8.3 it works but there is problem with call custom event
call custom event "%{world::%{_w}%::type}%" to details {_w}
and this doesn't work (tested on 1.7.5 and works)
and when i'm update it to 1.8.3> nametagedit doesn't work
and on newest version doesn't work skrayfall scoreboard

**Comment by Feerko** [comment]
I'm wrote to you with more details on discord.

**Comment by TlatoaniHJ** [comment]
Can you create a new issue using the template provided in the issue creator page?
