### ISSUE TITLE
Hide player in tablist and spectator game mode

### ISSUE THREAD

**Issue by Haesky** [MundoSK/MundoSK#24]
### Bug Report

Skript Version: 2.2 dev 36

MundoSK Version: 1.8.5

Minecraft Version: 1.12.2

### Steps to Reproduce the Issue
On an event or a command, if you hide player in tablist of player (or all players), it doesn't work... but if you put wait 5 ticks before (or wait x amount of time), it works, but after what the spectator game mode doesn't work correctly.

### Full Code
`on join:
    wait 5 ticks
    hide player in tablist of all players`

### Errors on Reload (if applicable)
No errors.

### Console Errors (if applicable)
No console errors.

### Other Useful Info (ex. addons and plugins you are using)
I'm using a lot of add-ons:
- SkRayFall
- Skellett
- MundoSK
- skript-ping
- SkQuery
- SkExtras
- SkUtilities

For the tablist I must have ProtocolLib as well.

### Troubleshooting

Have you tried looking in the documentation:
Yes, I've tried to use others syntaxes.
Have you tried looking in the forums:
I've tried to, a lot of times... it seems that the problem have been already done, but due to a plugin. (I can't refind the post, it was on spigot forum.)

What other methods have you tried to fix it:
I've tried the other syntaxes, to hide player in a different way, etc... but when I put "wait 5 ticks", the player is hidden but the game mode 3 doesn't work correctly.

### Additional Info
I've remade this issue in a local server, with a few add-ons and the same problem appears.
(So maybe the issue could come from the add-on that I've added, but I don't think so)

**Comment by TlatoaniHJ** [comment]
From my testing it seems like if the player is not present in their own tablist, spectator mode will not work correctly. There doesn't seem to be any way to fix this, other than to just have spectators see their own tab in tablist. You can still have them be hidden in other players' tablist and it will work fine, as long as they are visible in their own tablist.

**Comment by Haesky** [comment]
Okay thanks for help. I’m gonna check this tonight, but if anyone has the solution to hide the player from his tab list, it would be nice
