### ISSUE TITLE
ObjectEnum from protocollib has been refactored and causes ClassDefNotFoundErrors

### ISSUE THREAD

**Issue by CC007** [MundoSK/MundoSK#6]
https://github.com/aadnk/ProtocolLib/commit/1be94aad784913aa8b85d7733491461b446d69b0#diff-0333981e516a8aa0251a04d986666843 is the commit where it changed.

**Comment by TlatoaniHJ** [comment]
This issue should have been fixed with the latest MundoSK BETA versions. If it is still occurring, please post the specific error you are receiving.
