### ISSUE TITLE
Minor syntax conflict

### ISSUE THREAD

**Issue by melinstagibson** [MundoSK/MundoSK#9]
Just ran into a conflict with MundoSk and vanilla skript.

Vanilla Skript (Amount Expression):
(amount|number|size) of %objects%

MundoSk (ExprPropertyOfBorder):
(0¦(diameter|size)|1¦damage amount|2¦damage buffer|3¦warning distance|4¦warning time) of %world%

Affected Skript:
```
command /arenatest:
        permission: *
        trigger:
                clear {arenakits::*}
                add "CUSTOM", "test" and "noob" to {arenakits::*}
                send "%size of {arenakits::*}%"
```
Not really an issue if you dont use size of... which i did

**Comment by TlatoaniHJ** [comment]
Can you give MC version, Skript version, MundoSK version

**Comment by Snow-Pyon** [comment]
I can confirm this, using Skript dev30d in my 1.12.1 server with MundoSK 1.7.5-BETA.10.8

**Comment by TlatoaniHJ** [comment]
This appears to be an issue with Skript dev30d - usually this should not conflict as the `size of %objects%` expression requires a plural expression and the `size of %world%` expression expects a singular world expression. From other users' testing, it appears to be working fine in dev29. I won't be able to test myself for a few days, but I recommend if you want that someone can report it in the issue tracker for bensku Skript.

**Comment by TlatoaniHJ** [comment]
This should fix your issue: https://forums.skunity.com/threads/mundosk.165/page-7#post-21417
